use optd_dsl::analyzer::hir::Expr::*;
use optd_dsl::analyzer::hir::*;

/// Defines a join commute rule.
pub fn join_commute() -> Expr {
    Let(
        "right_indices".to_string(),
        Binary(
            Call(Ref("0".to_string()).into(), vec![]).into(),
            BinOp::Range,
            Call(
                Ref("schema_len".to_string()).into(),
                vec![Ref("right".to_string()).into()],
            )
            .into(),
        )
        .into(),
        Let(
            "left_indices".to_string(),
            Binary(
                Call(Ref("0".to_string()).into(), vec![]).into(),
                BinOp::Range,
                Call(
                    Ref("schema_len".to_string()).into(),
                    vec![Ref("left".to_string()).into()],
                )
                .into(),
            )
            .into(),
            Let(
                "remapping".to_string(),
                Call(
                    Ref("to_map".to_string()).into(),
                    vec![Binary(
                        Call(
                            Ref("map".to_string()).into(),
                            vec![
                                Ref("left_indices".to_string()).into(),
                                CoreExpr(CoreData::Function(FunKind::Closure(
                                    vec!["i".to_string()],
                                    CoreExpr(CoreData::Tuple(vec![
                                        Ref("i".to_string()).into(),
                                        Binary(
                                            Ref("i".to_string()).into(),
                                            BinOp::Add,
                                            Ref("right_len".to_string()).into(),
                                        )
                                        .into(),
                                    ]))
                                    .into(),
                                )))
                                .into(),
                            ],
                        )
                        .into(),
                        BinOp::Concat,
                        Call(
                            Ref("map".to_string()).into(),
                            vec![
                                Ref("right_indices".to_string()).into(),
                                CoreExpr(CoreData::Function(FunKind::Closure(
                                    vec!["i".to_string()],
                                    CoreExpr(CoreData::Tuple(vec![
                                        Binary(
                                            Ref("left_len".to_string()).into(),
                                            BinOp::Add,
                                            Ref("i".to_string()).into(),
                                        )
                                        .into(),
                                        Ref("i".to_string()).into(),
                                    ]))
                                    .into(),
                                )))
                                .into(),
                            ],
                        )
                        .into(),
                    )
                    .into()],
                )
                .into(),
                CoreExpr(CoreData::Struct(
                    "Project".to_string(),
                    vec![
                        CoreExpr(CoreData::Struct(
                            "Join".to_string(),
                            vec![
                                Ref("right".to_string()).into(),
                                Ref("left".to_string()).into(),
                                CoreExpr(CoreData::Literal(Literal::String("Inner".to_string())))
                                    .into(),
                                Call(
                                    Ref("remap".to_string()).into(),
                                    vec![
                                        Ref("cond".to_string()).into(),
                                        Ref("remapping".to_string()).into(),
                                    ],
                                )
                                .into(),
                            ],
                        ))
                        .into(),
                        Call(
                            Ref("to_array".to_string()).into(),
                            vec![Call(
                                Ref("map".to_string()).into(),
                                vec![
                                    Ref("right_indices".to_string()).into(),
                                    CoreExpr(CoreData::Function(FunKind::Closure(
                                        vec!["i".to_string()],
                                        CoreExpr(CoreData::Struct(
                                            "ColumnRef".to_string(),
                                            vec![Ref("i".to_string()).into()],
                                        ))
                                        .into(),
                                    )))
                                    .into(),
                                ],
                            )
                            .into()],
                        )
                        .into(),
                    ],
                ))
                .into(),
            )
            .into(),
        )
        .into(),
    )
}
