# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
# The file diesel will write the generated schema to.
file = "optd/src/storage/schema.rs"


# A column of type `INTEGER PRIMARY KEY` becomes an alias for the 64-bit signed integer `ROWID`. 
# See https://sqlite.org/autoinc.html for more details.
sqlite_integer_primary_key_is_bigint = true

[migrations_directory]
# The directory where the migration files are located.
dir = "optd/migrations"
