[package]
name = "optd-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
optd = { path = "../optd" }

clap = { version = "4.5.37", features = ["derive"] }
colored = "3.0.0"
tokio = "1.44.2"
