[package]
name = "optd-dsl"
version = "0.1.0"
edition = "2021"

[dependencies]
optd-core = { path = "../optd-core" }
chumsky = "0.9.3"
ariadne = "0.5.0"
ordered-float = "4.6.0"
anyhow.workspace = true
async-recursion.workspace = true
futures = "0.3.31"
itertools = "0.14.0"
