[package]
name = "optd-dsl"
version = "0.1.0"
edition = "2021"

[dependencies]
optd-core = { path = "../optd-core" }
chumsky = "0.9.3"
ariadne = "0.5.0"
ordered-float = "5.0.0"
futures = "0.3.31"
tokio.workspace = true
async-recursion.workspace = true
enum_dispatch = "0.3.13"
