[package]
name = "optd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
diesel.workspace = true
diesel_migrations.workspace = true
dotenvy.workspace = true
libsqlite3-sys.workspace = true
