[package]
name = "optd-datafusion"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait = "0.1.85"
datafusion = "45.0.0"
futures = "0.3.31"
itertools = "0.14.0"
tokio.workspace = true
trait-variant.workspace = true 
optd-core = { path = "../optd-core" }
async-recursion.workspace = true

