-- TPC-H Q2
select
        s_acctbal,
        s_name,
        n_name,
        p_partkey,
        p_mfgr,
        s_address,
        s_phone,
        s_comment
from
        part,
        supplier,
        partsupp,
        nation,
        region
where
        p_partkey = ps_partkey
        and s_suppkey = ps_suppkey
and p_size = 4
and p_type like '%TIN'
        and s_nationkey = n_nationkey
        and n_regionkey = r_regionkey
        and r_name = 'AFRICA'
        and ps_supplycost = (
                select
                        min(ps_supplycost)
                from
                        partsupp,
                        supplier,
                        nation,
                        region
                where
                        p_partkey = ps_partkey
                        and s_suppkey = ps_suppkey
                        and s_nationkey = n_nationkey
                        and n_regionkey = r_regionkey
                        and r_name = 'AFRICA'
        )
order by
    s_acctbal desc,
    n_name,
    s_name,
    p_partkey
limit 100;

/*
logical_plan after optd-initial:
Limit { .skip: 0::bigint, .fetch: 100::bigint, (.output_columns): __internal_#16.n_name(#16.2), __internal_#16.p_mfgr(#16.4), __internal_#16.p_partkey(#16.3), __internal_#16.s_acctbal(#16.0), __internal_#16.s_address(#16.5), __internal_#16.s_comment(#16.7), __internal_#16.s_name(#16.1), __internal_#16.s_phone(#16.6), (.cardinality): 0.00 }
└── OrderBy { ordering_exprs: [ __internal_#16.s_acctbal(#16.0) DESC, __internal_#16.n_name(#16.2) ASC, __internal_#16.s_name(#16.1) ASC, __internal_#16.p_partkey(#16.3) ASC ], (.output_columns): __internal_#16.n_name(#16.2), __internal_#16.p_mfgr(#16.4), __internal_#16.p_partkey(#16.3), __internal_#16.s_acctbal(#16.0), __internal_#16.s_address(#16.5), __internal_#16.s_comment(#16.7), __internal_#16.s_name(#16.1), __internal_#16.s_phone(#16.6), (.cardinality): 0.00 }
    └── Project { .table_index: 16, .projections: [ __internal_#15.s_acctbal(#15.14), __internal_#15.s_name(#15.10), __internal_#15.n_name(#15.22), __internal_#15.p_partkey(#15.0), __internal_#15.p_mfgr(#15.2), __internal_#15.s_address(#15.11), __internal_#15.s_phone(#15.13), __internal_#15.s_comment(#15.15) ], (.output_columns): __internal_#16.n_name(#16.2), __internal_#16.p_mfgr(#16.4), __internal_#16.p_partkey(#16.3), __internal_#16.s_acctbal(#16.0), __internal_#16.s_address(#16.5), __internal_#16.s_comment(#16.7), __internal_#16.s_name(#16.1), __internal_#16.s_phone(#16.6), (.cardinality): 0.00 }
        └── Project
            ├── .table_index: 15
            ├── .projections: [ __internal_#14.p_partkey(#14.0), __internal_#14.p_name(#14.1), __internal_#14.p_mfgr(#14.2), __internal_#14.p_brand(#14.3), __internal_#14.p_type(#14.4), __internal_#14.p_size(#14.5), __internal_#14.p_container(#14.6), __internal_#14.p_retailprice(#14.7), __internal_#14.p_comment(#14.8), __internal_#14.s_suppkey(#14.9), __internal_#14.s_name(#14.10), __internal_#14.s_address(#14.11), __internal_#14.s_nationkey(#14.12), __internal_#14.s_phone(#14.13), __internal_#14.s_acctbal(#14.14), __internal_#14.s_comment(#14.15), __internal_#14.ps_partkey(#14.16), __internal_#14.ps_suppkey(#14.17), __internal_#14.ps_availqty(#14.18), __internal_#14.ps_supplycost(#14.19), __internal_#14.ps_comment(#14.20), __internal_#14.n_nationkey(#14.21), __internal_#14.n_name(#14.22), __internal_#14.n_regionkey(#14.23), __internal_#14.n_comment(#14.24), __internal_#14.r_regionkey(#14.25), __internal_#14.r_name(#14.26), __internal_#14.r_comment(#14.27) ]
            ├── (.output_columns): __internal_#15.n_comment(#15.24), __internal_#15.n_name(#15.22), __internal_#15.n_nationkey(#15.21), __internal_#15.n_regionkey(#15.23), __internal_#15.p_brand(#15.3), __internal_#15.p_comment(#15.8), __internal_#15.p_container(#15.6), __internal_#15.p_mfgr(#15.2), __internal_#15.p_name(#15.1), __internal_#15.p_partkey(#15.0), __internal_#15.p_retailprice(#15.7), __internal_#15.p_size(#15.5), __internal_#15.p_type(#15.4), __internal_#15.ps_availqty(#15.18), __internal_#15.ps_comment(#15.20), __internal_#15.ps_partkey(#15.16), __internal_#15.ps_suppkey(#15.17), __internal_#15.ps_supplycost(#15.19), __internal_#15.r_comment(#15.27), __internal_#15.r_name(#15.26), __internal_#15.r_regionkey(#15.25), __internal_#15.s_acctbal(#15.14), __internal_#15.s_address(#15.11), __internal_#15.s_comment(#15.15), __internal_#15.s_name(#15.10), __internal_#15.s_nationkey(#15.12), __internal_#15.s_phone(#15.13), __internal_#15.s_suppkey(#15.9)
            ├── (.cardinality): 0.00
            └── Project
                ├── .table_index: 14
                ├── .projections: [ part.p_partkey(#1.0), part.p_name(#1.1), part.p_mfgr(#1.2), part.p_brand(#1.3), part.p_type(#1.4), part.p_size(#1.5), part.p_container(#1.6), part.p_retailprice(#1.7), part.p_comment(#1.8), supplier.s_suppkey(#3.0), supplier.s_name(#3.1), supplier.s_address(#3.2), supplier.s_nationkey(#3.3), supplier.s_phone(#3.4), supplier.s_acctbal(#3.5), supplier.s_comment(#3.6), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_availqty(#2.2), partsupp.ps_supplycost(#2.3), partsupp.ps_comment(#2.4), nation.n_nationkey(#4.0), nation.n_name(#4.1), nation.n_regionkey(#4.2), nation.n_comment(#4.3), region.r_regionkey(#5.0), region.r_name(#5.1), region.r_comment(#5.2), __scalar_sq_1.min(partsupp.ps_supplycost)(#13.0), __scalar_sq_1.ps_partkey(#13.1), __scalar_sq_1.__always_true(#13.2) ]
                ├── (.output_columns): __internal_#14.__always_true(#14.30), __internal_#14.min(partsupp.ps_supplycost)(#14.28), __internal_#14.n_comment(#14.24), __internal_#14.n_name(#14.22), __internal_#14.n_nationkey(#14.21), __internal_#14.n_regionkey(#14.23), __internal_#14.p_brand(#14.3), __internal_#14.p_comment(#14.8), __internal_#14.p_container(#14.6), __internal_#14.p_mfgr(#14.2), __internal_#14.p_name(#14.1), __internal_#14.p_partkey(#14.0), __internal_#14.p_retailprice(#14.7), __internal_#14.p_size(#14.5), __internal_#14.p_type(#14.4), __internal_#14.ps_availqty(#14.18), __internal_#14.ps_comment(#14.20), __internal_#14.ps_partkey(#14.16), __internal_#14.ps_partkey(#14.29), __internal_#14.ps_suppkey(#14.17), __internal_#14.ps_supplycost(#14.19), __internal_#14.r_comment(#14.27), __internal_#14.r_name(#14.26), __internal_#14.r_regionkey(#14.25), __internal_#14.s_acctbal(#14.14), __internal_#14.s_address(#14.11), __internal_#14.s_comment(#14.15), __internal_#14.s_name(#14.10), __internal_#14.s_nationkey(#14.12), __internal_#14.s_phone(#14.13), __internal_#14.s_suppkey(#14.9)
                ├── (.cardinality): 0.00
                └── Join { .join_type: Inner, .implementation: None, .join_cond: (part.p_partkey(#1.0) = __scalar_sq_1.ps_partkey(#13.1)) AND (partsupp.ps_supplycost(#2.3) = __scalar_sq_1.min(partsupp.ps_supplycost)(#13.0)), (.output_columns): __scalar_sq_1.__always_true(#13.2), __scalar_sq_1.min(partsupp.ps_supplycost)(#13.0), __scalar_sq_1.ps_partkey(#13.1), nation.n_comment(#4.3), nation.n_name(#4.1), nation.n_nationkey(#4.0), nation.n_regionkey(#4.2), part.p_brand(#1.3), part.p_comment(#1.8), part.p_container(#1.6), part.p_mfgr(#1.2), part.p_name(#1.1), part.p_partkey(#1.0), part.p_retailprice(#1.7), part.p_size(#1.5), part.p_type(#1.4), partsupp.ps_availqty(#2.2), partsupp.ps_comment(#2.4), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), region.r_comment(#5.2), region.r_name(#5.1), region.r_regionkey(#5.0), supplier.s_acctbal(#3.5), supplier.s_address(#3.2), supplier.s_comment(#3.6), supplier.s_name(#3.1), supplier.s_nationkey(#3.3), supplier.s_phone(#3.4), supplier.s_suppkey(#3.0), (.cardinality): 0.00 }
                    ├── Join { .join_type: Inner, .implementation: None, .join_cond: (nation.n_regionkey(#4.2) = region.r_regionkey(#5.0)), (.output_columns): nation.n_comment(#4.3), nation.n_name(#4.1), nation.n_nationkey(#4.0), nation.n_regionkey(#4.2), part.p_brand(#1.3), part.p_comment(#1.8), part.p_container(#1.6), part.p_mfgr(#1.2), part.p_name(#1.1), part.p_partkey(#1.0), part.p_retailprice(#1.7), part.p_size(#1.5), part.p_type(#1.4), partsupp.ps_availqty(#2.2), partsupp.ps_comment(#2.4), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), region.r_comment(#5.2), region.r_name(#5.1), region.r_regionkey(#5.0), supplier.s_acctbal(#3.5), supplier.s_address(#3.2), supplier.s_comment(#3.6), supplier.s_name(#3.1), supplier.s_nationkey(#3.3), supplier.s_phone(#3.4), supplier.s_suppkey(#3.0), (.cardinality): 0.00 }
                    │   ├── Join { .join_type: Inner, .implementation: None, .join_cond: (supplier.s_nationkey(#3.3) = nation.n_nationkey(#4.0)), (.output_columns): nation.n_comment(#4.3), nation.n_name(#4.1), nation.n_nationkey(#4.0), nation.n_regionkey(#4.2), part.p_brand(#1.3), part.p_comment(#1.8), part.p_container(#1.6), part.p_mfgr(#1.2), part.p_name(#1.1), part.p_partkey(#1.0), part.p_retailprice(#1.7), part.p_size(#1.5), part.p_type(#1.4), partsupp.ps_availqty(#2.2), partsupp.ps_comment(#2.4), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), supplier.s_acctbal(#3.5), supplier.s_address(#3.2), supplier.s_comment(#3.6), supplier.s_name(#3.1), supplier.s_nationkey(#3.3), supplier.s_phone(#3.4), supplier.s_suppkey(#3.0), (.cardinality): 0.00 }
                    │   │   ├── Join { .join_type: Inner, .implementation: None, .join_cond: (partsupp.ps_suppkey(#2.1) = supplier.s_suppkey(#3.0)), (.output_columns): part.p_brand(#1.3), part.p_comment(#1.8), part.p_container(#1.6), part.p_mfgr(#1.2), part.p_name(#1.1), part.p_partkey(#1.0), part.p_retailprice(#1.7), part.p_size(#1.5), part.p_type(#1.4), partsupp.ps_availqty(#2.2), partsupp.ps_comment(#2.4), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), supplier.s_acctbal(#3.5), supplier.s_address(#3.2), supplier.s_comment(#3.6), supplier.s_name(#3.1), supplier.s_nationkey(#3.3), supplier.s_phone(#3.4), supplier.s_suppkey(#3.0), (.cardinality): 0.00 }
                    │   │   │   ├── Join { .join_type: Inner, .implementation: None, .join_cond: (part.p_partkey(#1.0) = partsupp.ps_partkey(#2.0)), (.output_columns): part.p_brand(#1.3), part.p_comment(#1.8), part.p_container(#1.6), part.p_mfgr(#1.2), part.p_name(#1.1), part.p_partkey(#1.0), part.p_retailprice(#1.7), part.p_size(#1.5), part.p_type(#1.4), partsupp.ps_availqty(#2.2), partsupp.ps_comment(#2.4), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), (.cardinality): 0.00 }
                    │   │   │   │   ├── Select { .predicate: (part.p_size(#1.5) = 4::integer) AND (part.p_type(#1.4) LIKE %TIN::utf8_view), (.output_columns): part.p_brand(#1.3), part.p_comment(#1.8), part.p_container(#1.6), part.p_mfgr(#1.2), part.p_name(#1.1), part.p_partkey(#1.0), part.p_retailprice(#1.7), part.p_size(#1.5), part.p_type(#1.4), (.cardinality): 0.00 }
                    │   │   │   │   │   └── Get { .data_source_id: 3, .table_index: 1, .implementation: None, (.output_columns): part.p_brand(#1.3), part.p_comment(#1.8), part.p_container(#1.6), part.p_mfgr(#1.2), part.p_name(#1.1), part.p_partkey(#1.0), part.p_retailprice(#1.7), part.p_size(#1.5), part.p_type(#1.4), (.cardinality): 0.00 }
                    │   │   │   │   └── Get { .data_source_id: 5, .table_index: 2, .implementation: None, (.output_columns): partsupp.ps_availqty(#2.2), partsupp.ps_comment(#2.4), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), (.cardinality): 0.00 }
                    │   │   │   └── Get { .data_source_id: 4, .table_index: 3, .implementation: None, (.output_columns): supplier.s_acctbal(#3.5), supplier.s_address(#3.2), supplier.s_comment(#3.6), supplier.s_name(#3.1), supplier.s_nationkey(#3.3), supplier.s_phone(#3.4), supplier.s_suppkey(#3.0), (.cardinality): 0.00 }
                    │   │   └── Get { .data_source_id: 1, .table_index: 4, .implementation: None, (.output_columns): nation.n_comment(#4.3), nation.n_name(#4.1), nation.n_nationkey(#4.0), nation.n_regionkey(#4.2), (.cardinality): 0.00 }
                    │   └── Select { .predicate: region.r_name(#5.1) = AFRICA::utf8_view, (.output_columns): region.r_comment(#5.2), region.r_name(#5.1), region.r_regionkey(#5.0), (.cardinality): 0.00 }
                    │       └── Get { .data_source_id: 2, .table_index: 5, .implementation: None, (.output_columns): region.r_comment(#5.2), region.r_name(#5.1), region.r_regionkey(#5.0), (.cardinality): 0.00 }
                    └── Remap { .table_index: 13, (.output_columns): __scalar_sq_1.__always_true(#13.2), __scalar_sq_1.min(partsupp.ps_supplycost)(#13.0), __scalar_sq_1.ps_partkey(#13.1), (.cardinality): 0.20 }
                        └── Project { .table_index: 12, .projections: [ __internal_#11.min(partsupp.ps_supplycost)(#11.2), partsupp.ps_partkey(#2.0), __internal_#11.__always_true(#11.1) ], (.output_columns): __internal_#12.__always_true(#12.2), __internal_#12.min(partsupp.ps_supplycost)(#12.0), __internal_#12.ps_partkey(#12.1), (.cardinality): 0.20 }
                            └── Project { .table_index: 11, .projections: [ partsupp.ps_partkey(#6.0), true::boolean, __internal_#10.min(partsupp.ps_supplycost)(#10.0) ], (.output_columns): __internal_#11.__always_true(#11.1), __internal_#11.min(partsupp.ps_supplycost)(#11.2), __internal_#11.ps_partkey(#11.0), (.cardinality): 0.20 }
                                └── Aggregate { .aggregate_table_index: 10, .implementation: None, .exprs: min(partsupp.ps_supplycost(#6.3)), .keys: partsupp.ps_partkey(#6.0), (.output_columns): __internal_#10.min(partsupp.ps_supplycost)(#10.0), partsupp.ps_partkey(#6.0), (.cardinality): 0.20 }
                                    └── Join { .join_type: Inner, .implementation: None, .join_cond: (nation.n_regionkey(#8.2) = region.r_regionkey(#9.0)), (.output_columns): nation.n_comment(#8.3), nation.n_name(#8.1), nation.n_nationkey(#8.0), nation.n_regionkey(#8.2), partsupp.ps_availqty(#6.2), partsupp.ps_comment(#6.4), partsupp.ps_partkey(#6.0), partsupp.ps_suppkey(#6.1), partsupp.ps_supplycost(#6.3), region.r_comment(#9.2), region.r_name(#9.1), region.r_regionkey(#9.0), supplier.s_acctbal(#7.5), supplier.s_address(#7.2), supplier.s_comment(#7.6), supplier.s_name(#7.1), supplier.s_nationkey(#7.3), supplier.s_phone(#7.4), supplier.s_suppkey(#7.0), (.cardinality): 0.00 }
                                        ├── Join { .join_type: Inner, .implementation: None, .join_cond: (supplier.s_nationkey(#7.3) = nation.n_nationkey(#8.0)), (.output_columns): nation.n_comment(#8.3), nation.n_name(#8.1), nation.n_nationkey(#8.0), nation.n_regionkey(#8.2), partsupp.ps_availqty(#6.2), partsupp.ps_comment(#6.4), partsupp.ps_partkey(#6.0), partsupp.ps_suppkey(#6.1), partsupp.ps_supplycost(#6.3), supplier.s_acctbal(#7.5), supplier.s_address(#7.2), supplier.s_comment(#7.6), supplier.s_name(#7.1), supplier.s_nationkey(#7.3), supplier.s_phone(#7.4), supplier.s_suppkey(#7.0), (.cardinality): 0.00 }
                                        │   ├── Join { .join_type: Inner, .implementation: None, .join_cond: (partsupp.ps_suppkey(#6.1) = supplier.s_suppkey(#7.0)), (.output_columns): partsupp.ps_availqty(#6.2), partsupp.ps_comment(#6.4), partsupp.ps_partkey(#6.0), partsupp.ps_suppkey(#6.1), partsupp.ps_supplycost(#6.3), supplier.s_acctbal(#7.5), supplier.s_address(#7.2), supplier.s_comment(#7.6), supplier.s_name(#7.1), supplier.s_nationkey(#7.3), supplier.s_phone(#7.4), supplier.s_suppkey(#7.0), (.cardinality): 0.00 }
                                        │   │   ├── Get { .data_source_id: 5, .table_index: 6, .implementation: None, (.output_columns): partsupp.ps_availqty(#6.2), partsupp.ps_comment(#6.4), partsupp.ps_partkey(#6.0), partsupp.ps_suppkey(#6.1), partsupp.ps_supplycost(#6.3), (.cardinality): 0.00 }
                                        │   │   └── Get { .data_source_id: 4, .table_index: 7, .implementation: None, (.output_columns): supplier.s_acctbal(#7.5), supplier.s_address(#7.2), supplier.s_comment(#7.6), supplier.s_name(#7.1), supplier.s_nationkey(#7.3), supplier.s_phone(#7.4), supplier.s_suppkey(#7.0), (.cardinality): 0.00 }
                                        │   └── Get { .data_source_id: 1, .table_index: 8, .implementation: None, (.output_columns): nation.n_comment(#8.3), nation.n_name(#8.1), nation.n_nationkey(#8.0), nation.n_regionkey(#8.2), (.cardinality): 0.00 }
                                        └── Select { .predicate: region.r_name(#9.1) = AFRICA::utf8_view, (.output_columns): region.r_comment(#9.2), region.r_name(#9.1), region.r_regionkey(#9.0), (.cardinality): 0.00 }
                                            └── Get { .data_source_id: 2, .table_index: 9, .implementation: None, (.output_columns): region.r_comment(#9.2), region.r_name(#9.1), region.r_regionkey(#9.0), (.cardinality): 0.00 }

physical_plan after optd-finalized:
Limit { .skip: 0::bigint, .fetch: 100::bigint, (.output_columns): __internal_#16.n_name(#16.2), __internal_#16.p_mfgr(#16.4), __internal_#16.p_partkey(#16.3), __internal_#16.s_acctbal(#16.0), __internal_#16.s_address(#16.5), __internal_#16.s_comment(#16.7), __internal_#16.s_name(#16.1), __internal_#16.s_phone(#16.6), (.cardinality): 0.00 }
└── EnforcerSort { tuple_ordering: [(#16.0, Desc), (#16.2, Asc), (#16.1, Asc), (#16.3, Asc)], (.output_columns): __internal_#16.n_name(#16.2), __internal_#16.p_mfgr(#16.4), __internal_#16.p_partkey(#16.3), __internal_#16.s_acctbal(#16.0), __internal_#16.s_address(#16.5), __internal_#16.s_comment(#16.7), __internal_#16.s_name(#16.1), __internal_#16.s_phone(#16.6), (.cardinality): 0.00 }
    └── Project { .table_index: 16, .projections: [ supplier.s_acctbal(#3.5), supplier.s_name(#3.1), nation.n_name(#4.1), part.p_partkey(#1.0), part.p_mfgr(#1.2), supplier.s_address(#3.2), supplier.s_phone(#3.4), supplier.s_comment(#3.6) ], (.output_columns): __internal_#16.n_name(#16.2), __internal_#16.p_mfgr(#16.4), __internal_#16.p_partkey(#16.3), __internal_#16.s_acctbal(#16.0), __internal_#16.s_address(#16.5), __internal_#16.s_comment(#16.7), __internal_#16.s_name(#16.1), __internal_#16.s_phone(#16.6), (.cardinality): 0.00 }
        └── Join
            ├── .join_type: Inner
            ├── .implementation: None
            ├── .join_cond: (part.p_partkey(#1.0) = __scalar_sq_1.ps_partkey(#13.1)) AND (partsupp.ps_supplycost(#2.3) = __scalar_sq_1.min(partsupp.ps_supplycost)(#13.0))
            ├── (.output_columns): __scalar_sq_1.__always_true(#13.2), __scalar_sq_1.min(partsupp.ps_supplycost)(#13.0), __scalar_sq_1.ps_partkey(#13.1), nation.n_name(#4.1), nation.n_nationkey(#4.0), nation.n_regionkey(#4.2), part.p_mfgr(#1.2), part.p_partkey(#1.0), part.p_size(#1.5), part.p_type(#1.4), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), region.r_name(#5.1), region.r_regionkey(#5.0), supplier.s_acctbal(#3.5), supplier.s_address(#3.2), supplier.s_comment(#3.6), supplier.s_name(#3.1), supplier.s_nationkey(#3.3), supplier.s_phone(#3.4), supplier.s_suppkey(#3.0)
            ├── (.cardinality): 0.00
            ├── Join
            │   ├── .join_type: Inner
            │   ├── .implementation: None
            │   ├── .join_cond: nation.n_regionkey(#4.2) = region.r_regionkey(#5.0)
            │   ├── (.output_columns): nation.n_name(#4.1), nation.n_nationkey(#4.0), nation.n_regionkey(#4.2), part.p_mfgr(#1.2), part.p_partkey(#1.0), part.p_size(#1.5), part.p_type(#1.4), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), region.r_name(#5.1), region.r_regionkey(#5.0), supplier.s_acctbal(#3.5), supplier.s_address(#3.2), supplier.s_comment(#3.6), supplier.s_name(#3.1), supplier.s_nationkey(#3.3), supplier.s_phone(#3.4), supplier.s_suppkey(#3.0)
            │   ├── (.cardinality): 0.00
            │   ├── Join { .join_type: Inner, .implementation: None, .join_cond: supplier.s_nationkey(#3.3) = nation.n_nationkey(#4.0), (.output_columns): nation.n_name(#4.1), nation.n_nationkey(#4.0), nation.n_regionkey(#4.2), part.p_mfgr(#1.2), part.p_partkey(#1.0), part.p_size(#1.5), part.p_type(#1.4), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), supplier.s_acctbal(#3.5), supplier.s_address(#3.2), supplier.s_comment(#3.6), supplier.s_name(#3.1), supplier.s_nationkey(#3.3), supplier.s_phone(#3.4), supplier.s_suppkey(#3.0), (.cardinality): 0.00 }
            │   │   ├── Join { .join_type: Inner, .implementation: None, .join_cond: partsupp.ps_suppkey(#2.1) = supplier.s_suppkey(#3.0), (.output_columns): part.p_mfgr(#1.2), part.p_partkey(#1.0), part.p_size(#1.5), part.p_type(#1.4), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), supplier.s_acctbal(#3.5), supplier.s_address(#3.2), supplier.s_comment(#3.6), supplier.s_name(#3.1), supplier.s_nationkey(#3.3), supplier.s_phone(#3.4), supplier.s_suppkey(#3.0), (.cardinality): 0.00 }
            │   │   │   ├── Join { .join_type: Inner, .implementation: None, .join_cond: part.p_partkey(#1.0) = partsupp.ps_partkey(#2.0), (.output_columns): part.p_mfgr(#1.2), part.p_partkey(#1.0), part.p_size(#1.5), part.p_type(#1.4), partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), (.cardinality): 0.00 }
            │   │   │   │   ├── Select { .predicate: (part.p_size(#1.5) = 4::integer) AND (part.p_type(#1.4) LIKE %TIN::utf8_view), (.output_columns): part.p_mfgr(#1.2), part.p_partkey(#1.0), part.p_size(#1.5), part.p_type(#1.4), (.cardinality): 0.00 }
            │   │   │   │   │   └── Get { .data_source_id: 3, .table_index: 1, .implementation: None, (.output_columns): part.p_mfgr(#1.2), part.p_partkey(#1.0), part.p_size(#1.5), part.p_type(#1.4), (.cardinality): 0.00 }
            │   │   │   │   └── Get { .data_source_id: 5, .table_index: 2, .implementation: None, (.output_columns): partsupp.ps_partkey(#2.0), partsupp.ps_suppkey(#2.1), partsupp.ps_supplycost(#2.3), (.cardinality): 0.00 }
            │   │   │   └── Get { .data_source_id: 4, .table_index: 3, .implementation: None, (.output_columns): supplier.s_acctbal(#3.5), supplier.s_address(#3.2), supplier.s_comment(#3.6), supplier.s_name(#3.1), supplier.s_nationkey(#3.3), supplier.s_phone(#3.4), supplier.s_suppkey(#3.0), (.cardinality): 0.00 }
            │   │   └── Get { .data_source_id: 1, .table_index: 4, .implementation: None, (.output_columns): nation.n_name(#4.1), nation.n_nationkey(#4.0), nation.n_regionkey(#4.2), (.cardinality): 0.00 }
            │   └── Select { .predicate: region.r_name(#5.1) = AFRICA::utf8_view, (.output_columns): region.r_name(#5.1), region.r_regionkey(#5.0), (.cardinality): 0.00 }
            │       └── Get { .data_source_id: 2, .table_index: 5, .implementation: None, (.output_columns): region.r_name(#5.1), region.r_regionkey(#5.0), (.cardinality): 0.00 }
            └── Remap { .table_index: 13, (.output_columns): __scalar_sq_1.__always_true(#13.2), __scalar_sq_1.min(partsupp.ps_supplycost)(#13.0), __scalar_sq_1.ps_partkey(#13.1), (.cardinality): 0.20 }
                └── Project { .table_index: 12, .projections: [ __internal_#10.min(partsupp.ps_supplycost)(#10.0), partsupp.ps_partkey(#2.0), true::boolean ], (.output_columns): __internal_#12.__always_true(#12.2), __internal_#12.min(partsupp.ps_supplycost)(#12.0), __internal_#12.ps_partkey(#12.1), (.cardinality): 0.20 }
                    └── Aggregate { .aggregate_table_index: 10, .implementation: None, .exprs: min(partsupp.ps_supplycost(#6.3)), .keys: [ partsupp.ps_partkey(#6.0) ], (.output_columns): __internal_#10.min(partsupp.ps_supplycost)(#10.0), partsupp.ps_partkey(#6.0), (.cardinality): 0.20 }
                        └── Join { .join_type: Inner, .implementation: None, .join_cond: nation.n_regionkey(#8.2) = region.r_regionkey(#9.0), (.output_columns): nation.n_nationkey(#8.0), nation.n_regionkey(#8.2), partsupp.ps_partkey(#6.0), partsupp.ps_suppkey(#6.1), partsupp.ps_supplycost(#6.3), region.r_name(#9.1), region.r_regionkey(#9.0), supplier.s_nationkey(#7.3), supplier.s_suppkey(#7.0), (.cardinality): 0.00 }
                            ├── Join { .join_type: Inner, .implementation: None, .join_cond: supplier.s_nationkey(#7.3) = nation.n_nationkey(#8.0), (.output_columns): nation.n_nationkey(#8.0), nation.n_regionkey(#8.2), partsupp.ps_partkey(#6.0), partsupp.ps_suppkey(#6.1), partsupp.ps_supplycost(#6.3), supplier.s_nationkey(#7.3), supplier.s_suppkey(#7.0), (.cardinality): 0.00 }
                            │   ├── Join { .join_type: Inner, .implementation: None, .join_cond: partsupp.ps_suppkey(#6.1) = supplier.s_suppkey(#7.0), (.output_columns): partsupp.ps_partkey(#6.0), partsupp.ps_suppkey(#6.1), partsupp.ps_supplycost(#6.3), supplier.s_nationkey(#7.3), supplier.s_suppkey(#7.0), (.cardinality): 0.00 }
                            │   │   ├── Get { .data_source_id: 5, .table_index: 6, .implementation: None, (.output_columns): partsupp.ps_partkey(#6.0), partsupp.ps_suppkey(#6.1), partsupp.ps_supplycost(#6.3), (.cardinality): 0.00 }
                            │   │   └── Get { .data_source_id: 4, .table_index: 7, .implementation: None, (.output_columns): supplier.s_nationkey(#7.3), supplier.s_suppkey(#7.0), (.cardinality): 0.00 }
                            │   └── Get { .data_source_id: 1, .table_index: 8, .implementation: None, (.output_columns): nation.n_nationkey(#8.0), nation.n_regionkey(#8.2), (.cardinality): 0.00 }
                            └── Select { .predicate: region.r_name(#9.1) = AFRICA::utf8_view, (.output_columns): region.r_name(#9.1), region.r_regionkey(#9.0), (.cardinality): 0.00 }
                                └── Get { .data_source_id: 2, .table_index: 9, .implementation: None, (.output_columns): region.r_name(#9.1), region.r_regionkey(#9.0), (.cardinality): 0.00 }
*/

