[package]
name = "optd-core"
version = "0.1.0"
edition = "2021"

[dependencies]
# Pin more recent versions for `-Zminimal-versions`.
proc-macro2 = "1.0.60" # For a missing feature (https://github.com/rust-lang/rust/issues/113152).
tokio.workspace = true
anyhow.workspace = true
async-recursion.workspace = true
trait-variant.workspace = true
sqlx = { version = "0.8", features = [ "sqlite", "runtime-tokio", "migrate" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
dotenvy = "0.15"
pest = "2.7.15"
pest_derive = "2.7.15"
