[package]
name = "optd-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
async-recursion.workspace = true
trait-variant.workspace = true
proc-macro2.workspace = true
sqlx = { version = "0.8", features = [ "sqlite", "runtime-tokio", "migrate" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
dotenvy = "0.15"
ordered-float = { version = "5.0.0", features = ["serde"] }

async-trait = "0.1.85"
iceberg = "0.4.0"
